frase = input('Digite a frase: ')

frase_upper = frase.upper()

qttd_vogais = frase_upper.count('A')
qttd_vogais += frase_upper.count('Ã')
qttd_vogais += frase_upper.count('À')
qttd_vogais += frase_upper.count('Á')
qttd_vogais += frase_upper.count('Â')
qttd_vogais += frase_upper.count('E')
qttd_vogais += frase_upper.count('É')
qttd_vogais += frase_upper.count('Ê')
qttd_vogais += frase_upper.count('O')
qttd_vogais += frase_upper.count('Ô')
qttd_vogais += frase_upper.count('Õ')
qttd_vogais += frase_upper.count('Ó')
qttd_vogais += frase_upper.count('I')
qttd_vogais += frase_upper.count('Í')
qttd_vogais += frase_upper.count('U')
qttd_vogais += frase_upper.count('Ú')
print('A quantidade total de vogais é: ', qttd_vogais)